Importing the libraries

In [15]:
import numpy as np
import pandas as pd

Loading the dataset

In [2]:
df=pd.read_csv("fraudTrain.csv")

In [30]:
df=df.dropna()

In [31]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1.325376e+09,36.011293,-82.048315,0.0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1.325376e+09,49.159047,-118.186462,0.0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1.325376e+09,43.150704,-112.154481,0.0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1.325376e+09,47.034331,-112.561071,0.0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1.325376e+09,38.674999,-78.632459,0.0

Seperate X and y

In [41]:
X=df.drop(['is_fraud','Unnamed: 0'],axis=1)
y=df['is_fraud']

Convert date columns

In [33]:
X['trans_date_trans_time']=pd.to_datetime(X['trans_date_trans_time'])
X['hour']=X['trans_date_trans_time'].dt.hour
X['day']=X['trans_date_trans_time'].dt.day
X['month']=X['trans_date_trans_time'].dt.month
X['dob']=pd.to_datetime(X['dob'])
X['age']=2026-X['dob'].dt.year
X.drop(['trans_date_trans_time','dob'],axis=1,inplace=True)

Label Encode only text columns

In [34]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for col in X.select_dtypes(include="object").columns:
  X[col]=le.fit_transform(X[col].astype(str))

Scale everything

In [35]:
from sklearn.preprocessing import StandardScaler
s=StandardScaler()
X=s.fit_transform(X)

Training the model

In [37]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X,y)

LogisticRegression()

Importing the test dataset, perform preprocessing and evaluate

In [40]:
df_test=pd.read_csv('fraudTest.csv')
df_test=df_test.dropna()

In [42]:
X_test=df.drop(['is_fraud','Unnamed: 0'],axis=1)

In [45]:
X_test['trans_date_trans_time']=pd.to_datetime(X_test['trans_date_trans_time'])
X_test['hour']=X_test['trans_date_trans_time'].dt.hour
X_test['day']=X_test['trans_date_trans_time'].dt.day
X_test['month']=X_test['trans_date_trans_time'].dt.month
X_test['dob']=pd.to_datetime(X['dob'])
X_test['age']=2026-X_test['dob'].dt.year
X_test.drop(['trans_date_trans_time','dob'],axis=1,inplace=True)

In [46]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for col in X_test.select_dtypes(include="object").columns:
  X_test[col]=le.fit_transform(X_test[col].astype(str))

In [53]:
from sklearn.preprocessing import StandardScaler
s=StandardScaler()
X_test=s.fit_transform(X_test)

In [49]:
y_pred=model.predict(X_test)

In [60]:
pd.Series(y).value_counts()

is_fraud
0.0    61675
1.0      580
Name: count, dtype: int64

In [61]:
pd.Series(y_pred).value_counts()

0.0    62171
1.0       84
Name: count, dtype: int64

Inference: logistic Regression model doesn't perform well here